#! /usr/bin/env python
# -*- coding: utf-8 -*-

def main():
	
	return 0

## -------------------------------------------
## TEMPLATE

from sys import stdin
from sys import setrecursionlimit
from copy import deepcopy
from math import sqrt
from itertools import permutations
from itertools import combinations

def getline():
	return stdin.readline()

def getLineAs(tp):
	return map(tp, getline().split())

def array(n, init = 0):
	return [deepcopy(init) for i in range(n)]

if __name__ == "__main__":
	setrecursionlimit(1024 * 1024)
	main()
